//
// SpeechKit.h
//
// This file is a part of the Yandex SpeechKit project.
//
// (C) Copyright 2013 Yandex, LLC. All rights reserved.
//
// Author: Sergey Zimin <szimin@yandex-team.ru>
//

#import <Foundation/Foundation.h>

@protocol YSKRecognizerDelegate;

/*!
    @interface YSKRecognizer
    @brief The interface to a single-use Recognizer.
    @details The {@link YSKRecognizer} object manages the entire recognition process including audio recording, voice activity detection, server communication, and so on. 

    Recognizer is designed to carry out a single recognition and may not be reused. Subsequent recognitions should each be generated by creating a new {@link YSKRecognizer} object. 

    The recognizer notifies via {@link YSKRecognizerDelegate} interface about important events in the recognition process.

    @note SpeechKit shall be initialized via {@link YSKSpeechKit::configureWithAPIKey:} before creating any recognizer.

    @note The {@link YSKRecognizer} object may be created even before the initialization has been performed ({@link YSKInitializer}). In this case, the recognizer will initiate the initializer internally before the actual recognition.

    @note The recognizer initializes and holds several mutual resources, so two instances of the {@link YSKRecognizer} class may not co-exist. A new {@link YSKRecognizer} object may be created only after the current recognition is finished with either {@link YSKRecognizerDelegate::recognizer:didFailWithError:} or {@link YSKRecognizerDelegate::recognizer:didCompleteWithResults:} method invocation.
 */
@interface YSKRecognizer : NSObject

/*!
    @property delegate
    @brief The delegate object for the recognizer callbacks.
    @details The delegate will receive notifications when recording starts and finishes, when the recognition result is received, and when an error occurs.
 */
@property(nonatomic, weak) id<YSKRecognizerDelegate> delegate;

/*!
    @brief Initializes a single-use {@link YSKRecognizer} object.
    @details Call the {@link start} method to begin the recognition.
    @param language the language spoken by the user, specified in BCP 47 format (http://en.wikipedia.org/wiki/IETF_language_tag). BCP 47 expresses the language as an ISO 639 language code, followed by a dash "-", followed by the ISO 3166-1 country code. For example, an English speaker from the United States would be expressed as "en-US".
    @param model the language model to be used for recognition. This allows the server to better anticipate the type of phrases the user is likely to say and select an appropriate vocabulary of words that the user might say, and therefore has an impact on recognition accuracy.
    @return The {@link YSKRecognizer} object corresponding to the recognition request.
 */
- (instancetype)initWithLanguage:(NSString *)language model:(NSString *)model;

/*!
    @brief Release the resources used by the {@link YSKRecognizer} object.
 */
- (void)dealloc;

/*!
    @brief Checks whether the recognition is currently available.
    @note If the initialization has not been completed, the function always returns YES.
 */
+ (BOOL)isRecognitionAvailable;

/*!
    @brief Starts the recognition process.
    @details It might take time to initialize the audio device and establish a connection to the speech server. This means the recording will not start immediately after the function is invoked. When recording actually starts, the {@link YSKRecognizerDelegate::recognizerDidStartRecording:} method is called.
 */
- (void)start;

/*! 
    @brief Force finish sound recording and complete the request out.
    @details Normally this method should not be invoked, because Voice Activity Detector (VAD) detects the end of speech automatically. However, this method is needed when VAD is disabled or it does not detect the end of speech properly.
 */
- (void)finishRecording;

/*!
    @brief Cancels the recognition request.
    @details The method cancels the recognition request at any stage of the operation. The audio recording stops and network communication breaks if needed.
    @note The function cancels the request asynchronously. This means that the recognition is not cancelled immediately after invoking this function and it still might invoke callbacks. 
    @note The recognizer will be destroied automatically when either {@link YSKRecognizerDelegate::recognizer:didFailWithError:} or {@link YSKRecognizerDelegate::recognizer:didCompleteWithResults:} method is invoked.
 */
- (void)cancel;

/*!
    @property language
    @brief The language of the recognition request.
 */
@property (nonatomic, assign, readonly, getter=getLangauge) NSString* language;

/*!
    @property model
    @brief The model of the recognition request.
 */
@property (nonatomic, assign, readonly, getter=getModel) NSString* model;

/*!
    @property VADEnabled
    @brief Controls the behavior of the Voice Activity Detector (VAD).
    @details If VAD is disabled, SpeechKit will not detect the end of an utterance automatically. In this case, call {@link finishRecording:} to finish the recording and proceed with the recognition.
 */
@property (nonatomic, assign, readwrite, getter=isVADEnabled) BOOL VADEnabled;

@end
